# Generated by Django 4.2.9 on 2024-06-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('Domain', models.CharField(max_length=100)),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('Domain', models.CharField(max_length=100)),
                ('Duration', models.IntegerField()),
            ],
        ),
    ]
