# Generated by Django 4.2.9 on 2024-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ie',
            name='Duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='we',
            name='Duration',
            field=models.CharField(max_length=100),
        ),
    ]
