# Generated by Django 4.2.9 on 2024-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ie_duration_alter_we_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('key_skills', models.CharField(max_length=100)),
                ('project_url', models.CharField(max_length=300)),
            ],
        ),
    ]
